
GRANT ALL PRIVILEGES ON DATABASE "Athena" to edulog;
GRANT USAGE ON SCHEMA public TO edulog;
GRANT ALL PRIVILEGES ON SCHEMA public TO edulog;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO edulog;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO edulog;
GRANT USAGE ON SCHEMA settings TO edulog;
GRANT ALL PRIVILEGES ON SCHEMA settings TO edulog;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA settings TO edulog;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA settings TO edulog;